### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by en-you** [LolWastedJS/erika-costell#1]
```js
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('main-node')
    at Manager.emit (events.js:300:17)
    at Node._error (REMOVED_PATH\node_modules\discord.js-andesite\build\api\Node.js:169:22)
    at WebSocket.emit (events.js:311:20)
    at abortHandshake (REMOVED_PATH\node_modules\ws\lib\websocket.js:697:15)
    at ClientRequest.<anonymous> (REMOVED_PATH\node_modules\ws\lib\websocket.js:579:7)    at ClientRequest.emit (events.js:311:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at Socket.socketOnData (_http_client.js:476:22)
    at Socket.emit (events.js:311:20) {
  code: 'ERR_UNHANDLED_ERROR',
  context: 'main-node'
}
```

When I am gonna run bot. This error occurs. I filled my lavalink information correctly.

**Comment by ghost** [comment]
Did you have same password as application.conf and the manager itself?

**Comment by viztea** [comment]
The client needs the correct host, and the port and password in your andesite.conf

**Comment by en-you** [comment]
Solved
